from src.logger import logging
from src.exception import CustomException
import sys





# try:
#     a = 2/0
# except Exception as e:
#     raise CustomException(e,sys)

# logging.info("Zero divide by 2")
# logging.info("Logging has started")

